apiVersion: v2
name: galaxy-deps
type: application
version: 1.0.0
description: Chart containing environmental dependencies needed by Galaxy. Galaxy is an open, web-based platform for accessible, reproducible, and transparent computational biomedical research.
icon: https://galaxyproject.org/images/galaxy-logos/galaxy_project_logo_square.png
dependencies:
  - name: cloudnative-pg
    repository: https://cloudnative-pg.github.io/charts/
    version: 0.23.0
    condition: postgresql.deploy
    # cannot alias due to: https://github.com/cloudnative-pg/charts/issues/351
    # alias: postgresql
    tags:
      - deploy-postgres
  - name: csi-s3
    repository: https://raw.githubusercontent.com/cloudve/helm-charts/master/
    version: 0.35.2
    condition: s3csi.deploy
    alias: s3csi
    tags:
      - deploy-s3csi
  - name: galaxy-cvmfs-csi
    repository: https://raw.githubusercontent.com/cloudve/helm-charts/master/
    version: 2.2.0
    condition: cvmfs.deploy
    alias: cvmfs
    tags:
      - deploy-cvmfs
  - name: rabbitmq-cluster-operator
    repository: https://charts.bitnami.com/bitnami
    version: 2.6.12
    condition: rabbitmq.deploy
    alias: rabbitmq
    tags:
      - deploy-rabbitmq
