cnpg:
  #- Whether to deploy the postgresl operator.
  #- In general, we recommend installing the operator globally in production.
  deploy: true
  # nameOverride is set to work around https://github.com/cloudnative-pg/charts/issues/351
  # See: https://github.com/cloudnative-pg/cloudnative-pg/issues/2466#issuecomment-2775117800
  nameOverride: cloudnative-pg
  image:
    repository: ksuderman/cloudnative-pg
    tag: "1.25.2"

#- Configuration block if `cvmfs` is used as `refdata.type`
cvmfs:
  #- Deploy the Galaxy-CVMFS-CSI Helm Chart. This is an optional dependency, and for production scenarios it should be deployed separately as a cluster-wide resource
  deploy: true
  storageClassName: "galaxy-cvmfs"
  cvmfscsi:
    cache:
      alien:
        enabled: false
        pvc:
          storageClass: ""

#- Configuration block if `s3csi` is used as the `refdata.type`
s3csi:
  #- Deploy the CSI-S3 Helm Chart. This is an optional dependency, and for production scenarios it should be deployed separately as a cluster-wide resource.
  deploy: false
  images:
    csi: cloudve/csi-s3:0.31.3
  secret:
    endpoint: https://s3.ap-southeast-2.amazonaws.com

rabbitmq:
  deploy: true
  nameOverride: rabbitmq
