{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-wait-for-cnpg
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "1"
spec:
  serviceAccountName: {{ .Release.Name }}-cnpg-wait
  containers:
    - name: wait
      image: bitnami/kubectl
      command:
        - kubectl
        - wait
        - --for=condition=ready
        - --selector=app.kubernetes.io/name=cloudnative-pg
        - --timeout=300s
        - pod
  restartPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-cnpg-wait
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-cnpg-wait
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "0"
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-cnpg-wait
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "0"
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-cnpg-wait
roleRef:
  kind: Role
  name: {{ .Release.Name }}-cnpg-wait
  apiGroup: rbac.authorization.k8s.io
{{- end }}
